from pathlib import Path
p=Path('/tmp/chain-feedback.py')
s=p.read_text()
old="function spawnNeutronBatch(count,{storm=false,cascade=false,rootId=null}={}){const root=rootId||startChainEvent(storm?'r':'neutron'),ids=[];let made=0;for(let i=0;i<count;i++){const id=spawnNeutron(root);if(id){made++;ids.push(id)}}if(made){state.neutronPulsesObserved++;if(storm)state.neutronStormsObserved++;renderNeutrons();if(storm||cascade)scheduleNeutronCascade(root,ids,{storm})}return made}"
new="function spawnNeutronBatch(count,{storm=false,cascade=false,rootId=null}={}){const root=rootId||null,ids=[];let made=0;for(let i=0;i<count;i++){const id=spawnNeutron(root);if(id){made++;ids.push(id)}}if(made){state.neutronPulsesObserved++;if(storm)state.neutronStormsObserved++;renderNeutrons();if(cascade){const eventRoot=root||startChainEvent(storm?'r':'neutron');ids.forEach(id=>{const n=state.neutrons.get(id);if(n)n.chainRoot=eventRoot});scheduleNeutronCascade(eventRoot,ids,{storm})}}return made}"
assert s.count(old)==1;s=s.replace(old,new,1)
needle='js = once(js, old_generated, new_generated, "generated neutron provenance")\n'
cap="function captureTag(x,y,text){if(!dom.fx||!Number.isFinite(x)||!Number.isFinite(y)||!text)return null;const d=document.createElement('div');d.className='capture-tag';d.style.left=x+'px';d.style.top=y+'px';d.textContent=text;dom.fx.appendChild(d);setTimeout(()=>d.remove(),780);return d}"
extra=f'''\n# A manual r-process capture may trigger a few trajectory-valid followers; ambient storms never auto-play.\nold_neutron_tail = "state.locked=false;ensureOpportunity();render();checkComplete();\\n}}\\n{cap}"\nnew_neutron_tail = "const stormFollowers=s.rprocess?[...state.neutrons.keys()].filter(nid=>nid!==id).slice(0,5):[];const stormRoot=stormFollowers.length?startChainEvent('r',p?.x,p?.y):null;state.locked=false;ensureOpportunity();render();checkComplete();if(stormRoot)scheduleNeutronCascade(stormRoot,stormFollowers,{{storm:true}});\\n}}\\n{cap}"\njs = once(js, old_neutron_tail, new_neutron_tail, "manual r-process cascade trigger")\n'''
assert needle in s;s=s.replace(needle,needle+extra,1)
olddefs='''old_cosmic_tail = "await afterNuclearAction();state.locked=false;render();checkComplete();if(!state.phaseDone)setTimeout(spawnCosmicRay,120)"\nnew_cosmic_tail = "await afterNuclearAction();state.locked=false;render();checkComplete();scheduleAutoFusionCascade(product.id,chainRoot,1,s.mode==='gamma'?'gamma':'nuclear');if(!state.phaseDone)setTimeout(spawnCosmicRay,120)"\n# This tail appears in the non-isotope branch once; isotope branch has an earlier return.\njs = once(js, old_cosmic_tail, new_cosmic_tail, "cosmic chain continuation")'''
newdefs='''old_cosmic_tail = "await afterNuclearAction();state.locked=false;render();checkComplete();if(!state.phaseDone)setTimeout(spawnCosmicRay,120)\\n}\\nfunction drawLines()"\nnew_cosmic_tail = "await afterNuclearAction();state.locked=false;render();checkComplete();scheduleAutoFusionCascade(product.id,chainRoot,1,s.mode==='gamma'?'gamma':'nuclear');if(!state.phaseDone)setTimeout(spawnCosmicRay,120)\\n}\\nfunction drawLines()"\njs = once(js, old_cosmic_tail, new_cosmic_tail, "cosmic chain continuation")'''
assert s.count(olddefs)==1;s=s.replace(olddefs,newdefs,1)
p.write_text(s)
