const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const engine=fs.readFileSync(path.join(root,'assets/js/ardua.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
function ok(cond,msg){if(!cond)throw new Error(msg);console.log('✓',msg)}
const ids=[...engine.matchAll(/id:'(rp_[a-z]+)'/g)].map(m=>m[1]);
ok(ids.length===24,'24 fases próprias do rp-process');
ok(new Set(ids).size===24,'IDs das fases rp são únicos');
const expected=['rp_cu','rp_zn','rp_ga','rp_ge','rp_as','rp_se','rp_br','rp_kr','rp_rb','rp_sr','rp_y','rp_zr','rp_nb','rp_mo','rp_tc','rp_ru','rp_rh','rp_pd','rp_ag','rp_cd','rp_in','rp_sn','rp_sb','rp_te'];
ok(expected.every(id=>ids.includes(id)),'sequência Cu→Te está completa');
ok(engine.includes("productMass:64")&&engine.includes('⁶⁴Ge'),'waiting point ⁶⁴Ge está explícito');
ok(engine.includes("productMass:68")&&engine.includes('⁶⁸Se'),'waiting point ⁶⁸Se está explícito');
ok(engine.includes("productMass:72")&&engine.includes('⁷²Kr'),'waiting point ⁷²Kr está explícito');
ok(engine.includes("mode:'rpCycle'")&&engine.includes('Sn ↔ Sb ↔ Te'),'ciclo terminal Sn–Sb–Te está configurado');
ok(engine.includes("fuel:'H'")&&engine.includes("fuel:'p'"),'há fases com H ionizável e com prótons livres');
ok(engine.includes('ionizeRpHydrogen')&&engine.includes('H → p + e⁻'),'ionização de Hidrogênio está implementada');
ok(engine.includes('rpPhotoReturns++')&&engine.includes('photodisintegration'),'competição (γ,p) está implementada');
ok(engine.includes("rpWaitDecays>=1")&&engine.includes("rpCyclesObserved>=1"),'waiting point e ciclo exigem observação antes de concluir');
ok(engine.includes("seedCount:1,menuTag:step.to")&&engine.includes("const step=rpStep(s),cells=activeCells().slice(),used=new Set(),seedCount=1"),'cada fase rp começa com exatamente uma semente direta');
ok(engine.includes("RP_FOUNDATION_STEPS")&&engine.includes("from:'Fe',to:'Co'")&&engine.includes("from:'Co',to:'Ni'"),'rp-process reconstrói Ni a partir da semente-base de Ferro');
ok(engine.includes("const hasRpRoute=[...state.pieces.values()].some")&&engine.includes("createPiece('Fe',cell,true)"),'segurança do rp-process repõe apenas matéria-base, nunca o precursor direto');
ok(engine.includes("configureSingleObjectiveIngredients(PHASES)")&&engine.includes("p.starterGroups=[[p.seed],...Array.from({length:baseCount},()=>['Fe'])]"),'fases s/r recebem uma única semente direta e Ferro para reconstrução');
ok(engine.includes("foundation_weak_s")&&engine.includes("foundation_agb_s")&&engine.includes("foundation_r"),'processos de nêutrons possuem rotas agregadas de reconstrução a partir de Ferro');
ok(engine.includes("configureNeutronGameplay(PHASES)")&&engine.includes("neutronPattern:'")===false,'mecânicas de nêutrons são configuradas por templates globais, não duplicadas nas fases');
ok(engine.includes("source22")&&engine.includes("Ne22")&&engine.includes("²²Ne + ⁴He → ²⁵Mg + n"),'fonte ²²Ne(α,n) está implementada');
ok(engine.includes("source13")&&engine.includes("C13")&&engine.includes("¹³C + ⁴He → ¹⁶O + n"),'fonte ¹³C(α,n) está implementada');
ok(engine.includes("scheduleNeutronBeta")&&engine.includes("resolvePendingNeutronBetas")&&engine.includes("neutronBetaPending"),'espera β− usa estado nuclear pendente');
ok(engine.includes("requiresNeutronBranch")&&engine.includes("captura antes do β−")&&engine.includes("neutronBranchesObserved"),'ramificações permitem captura antes de β−');
ok(engine.includes("neutronShellExposure")&&engine.includes("CASCA ATRAVESSADA")&&engine.includes("EXPOSIÇÃO"),'cascas mágicas exigem exposição acumulada');
ok(engine.includes("neutronPulseSize")&&engine.includes("spawnNeutronBatch")&&engine.includes("pulseStrong"),'pulsos de nêutrons variam o fluxo do processo-s');
ok(engine.includes("rStorm")&&engine.includes("rWave")&&engine.includes("neutronStormsObserved"),'processo-r possui tempestades e ondas de nêutrons');
ok(engine.includes("rFreezeout")&&engine.includes("FREEZE-OUT")&&engine.includes("neutronFreezeouts"),'freeze-out do processo-r está implementado como etapa própria');
ok(engine.includes("p.neutronBetaPending&&neutronGameplay(s).pattern!=='branch'"),'núcleos aguardando β− bloqueiam recaptura fora de ramificações');
ok(engine.includes("COULOMB_BLOCK_CHANCE_BY_RING=Object.freeze({0:0,1:0,2:.5,3:.6,4:.8})"),'Barreira de Coulomb usa 0/0/50/60/80% por camada');
ok(engine.includes("if(s.id==='coulomb_intro')return ring<=2?0:1"),'tutorial mantém Barreira de Coulomb determinística: anéis 0–2 livres e 3–4 bloqueados');
ok(engine.includes("COULOMB_EXEMPT_SYMS=new Set(['H','D','T'])"),'H, Deutério e Trítio permanecem isentos da Barreira de Coulomb');
ok(engine.includes('coulombRollBlocks(blockedCell,s,blockedPiece.sym)')&&engine.includes('coulombRollBlocks(cell,s,target.sym)'),'fusão e captura de prótons usam a chance radial da Barreira de Coulomb');
ok(engine.includes("coulomb:{title:'BARREIRA DE COULOMB',text:'Aproxime os átomos do núcleo estelar para diminuir a resistência.'}"),'tooltip da Barreira de Coulomb usa sempre a mensagem didática fixa');
ok(html.includes('assets/css/ardua.css')&&html.includes('assets/js/ardua.js'),'index.html continua apontando para assets estáticos');

ok(engine.includes('const RewardDirector=Object.freeze')&&engine.includes('const DiscoverySystem=Object.freeze')&&engine.includes('const AdaptiveAudio=Object.freeze'),'diretor de recompensas, descobertas e áudio adaptativo são globais');
ok(engine.includes("state.rewardDiscoveries")&&engine.includes("rewardAchievements")&&engine.includes("signatureSeen"),'Atlas e marcos audiovisuais persistem no save');
ok(engine.includes("state.chainCalloutTimer=setTimeout")&&engine.includes("},1850)"),'texto de cascata permanece legível por aproximadamente 1,85 s após a última atualização');
ok(engine.includes("CHAIN_AUTO_FLOW_FACTORS=Object.freeze([.25,.10,0])")&&engine.includes('CHAIN_MAX_PROGRESS_BONUS=.10'),'cascatas preservam crédito decrescente e teto de 10% do flowTarget');
ok(engine.includes('CHAIN_OBJECTIVE_PROGRESS_FLOOR=.75'),'objetivo científico preserva piso de 75% sem encerrar a fase sozinho');
ok(engine.includes("preparedContinuationForFusion")&&engine.includes("phenomenon:plannedChain"),'cadeias previamente posicionadas podem ser reconhecidas como rede preparada');
ok(engine.includes("playScientificSignature('supernova')")&&engine.includes("playScientificSignature('neutronStar')")&&engine.includes("playScientificSignature('blackHole')"),'Supernova, Estrela de Nêutrons e Buraco Negro possuem momentos de assinatura');
ok(engine.includes("C:'carbon'")&&engine.includes("Fe:'iron'")&&engine.includes("Au:'gold'")&&engine.includes("U:'uranium'"),'Carbono, Ferro, Ouro e Urânio possuem assinaturas científicas');
ok(engine.includes("setTimeout(()=>{if(phase()===s&&state.readyToAdvance)$('phaseEndBtn').classList.add('show')},720)"),'avanço da fase espera o beat audiovisual de conclusão');
ok(html.includes('id="discoveryAtlas"')&&html.includes('Atlas de descobertas'),'menu contém Atlas de descobertas persistente');
const css=fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8');
ok(css.includes('.chain-callout')&&css.includes('.reward-progress-aura')&&css.includes('.reward-spark'),'hierarquia visual inclui callout, aura persistente e partículas contidas');
ok(css.includes('@media(prefers-reduced-motion:reduce)'),'efeitos respeitam preferência de redução de movimento');
ok(engine.includes('function objectiveProgress(s=phase())')&&engine.includes('const done=objectiveSatisfied(s);if(done)return 1'),'barra possui progresso científico próprio e só libera 100% com objetivo satisfeito');
ok(engine.includes('const objective=objectiveProgress(s)')&&engine.includes('return Math.min(objective,flow)*100'),'PROGRESSO usa o menor avanço entre objetivo científico e flow');
ok(engine.includes("state.readyToAdvance?100:Math.min(99,Math.floor(p))"),'texto da barra não arredonda uma fase incompleta para 100%');
ok(engine.includes("fragilePhase.uniqueMatterObjective=true")&&engine.includes('objectiveLineages:new Set()'),'fase de Be-8 usa objetivo por linhagem de matéria');
ok(engine.includes('function mergeMatterLineages')&&engine.includes('function creditObjectiveLineage'),'proveniência de matéria é herdável e creditada por linhagem');
ok(engine.includes("createPiece('He',origin,false,{lineage})")&&engine.includes("createPiece('He',secondCell,false,{lineage})"),'decaimento de Be-8 devolve Hélios com a mesma proveniência');
ok(engine.includes("teachProductOnce('recycledMatter',t.x,t.y)")&&engine.includes('MATÉRIA RECICLADA · sem novo crédito'),'reciclagem repetida permanece válida mas não farma o objetivo');
ok(engine.includes('CHAIN_LESSON_BY_KIND')&&engine.includes('await teachChainEffectOnce(kind,product.x,product.y)'),'primeira cascata pausa para explicação antes da continuação automática');
ok(engine.includes("await teachProductOnce('neutronSource',at.x,at.y)")&&engine.includes("await teachProductOnce('freezeout',p.x,p.y)")&&engine.includes("await teachProductOnce('branching',p.x,p.y)"),'fontes, freeze-out e ramificações recebem tooltip antes do efeito');
ok(engine.includes("if(viable&&!photoReturn&&route.rp&&route.pattern==='waiting')await teachProductOnce('waitingPoint',target.x,target.y)"),'waiting point é explicado antes da animação de captura');
ok(engine.includes('const ObjectiveReactionMotif=Object.freeze')&&engine.includes("if(s.mode!=='fusion')return[]"),'Reaction Motif é um sistema global mas só escolhe receitas-alvo de fusão manual');
ok(engine.includes('r?.out===s.new')||engine.includes('r.out===s.new'),'receita-alvo do motif precisa produzir o objetivo científico da fase');
ok(engine.includes('state.chainAutoContext')&&engine.includes('objectiveMotifReactionEligible'),'cascatas automáticas não recebem a cerimônia completa do objetivo');
ok(engine.includes('objectiveMotifArmFirst(p)')&&engine.includes('objectiveMotifArmSecond(ex,[...state.selected])'),'primeiro e segundo reagentes da receita-alvo disparam notas próprias');
ok(engine.includes('objectiveMotifPlayNote(r,2)')&&engine.includes('objectiveMotifChord(ctx.r'),'alinhamento toca a terceira nota e o produto resolve com o acorde das três notas');
ok(engine.includes('objectiveMotifSelectionReady(r,cells)')&&engine.includes('objectiveLineageIsFresh'),'motif exige seleção manual pronta e respeita a proveniência anti-reciclagem');
ok(engine.includes('objectiveMotifBarrierBlocked(blockedPiece,r)'),'Barreira de Coulomb interrompe a resolução musical e rearma a tentativa');
ok(engine.includes('await objectiveMotifPrepare')&&engine.includes('await objectiveMotifConverge')&&engine.includes('await objectiveMotifReveal'),'reação-objetivo possui timeline visual preparar → convergir → revelar');
ok(css.includes('/* Objective Reaction Motif */')&&css.includes('.objective-motif-nucleus.result.visible'),'CSS contém a cerimônia visual central da reação-objetivo');
console.log('\nValidação estática do Ardua concluída.');
