const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const engine=fs.readFileSync(path.join(root,'assets/js/ardua.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const formationCss=fs.readFileSync(path.join(root,'assets/css/stellar-formation.css'),'utf8');
function ok(cond,msg){if(!cond)throw new Error(msg);console.log('✓',msg)}
const ids=[...engine.matchAll(/id:'(rp_[a-z]+)'/g)].map(m=>m[1]);
ok(ids.length===24,'24 fases próprias do rp-process');
ok(new Set(ids).size===24,'IDs das fases rp são únicos');
const expected=['rp_cu','rp_zn','rp_ga','rp_ge','rp_as','rp_se','rp_br','rp_kr','rp_rb','rp_sr','rp_y','rp_zr','rp_nb','rp_mo','rp_tc','rp_ru','rp_rh','rp_pd','rp_ag','rp_cd','rp_in','rp_sn','rp_sb','rp_te'];
ok(expected.every(id=>ids.includes(id)),'sequência Cu→Te está completa');
ok(engine.includes("productMass:64")&&engine.includes('⁶⁴Ge'),'waiting point ⁶⁴Ge está explícito');
ok(engine.includes("productMass:68")&&engine.includes('⁶⁸Se'),'waiting point ⁶⁸Se está explícito');
ok(engine.includes("productMass:72")&&engine.includes('⁷²Kr'),'waiting point ⁷²Kr está explícito');
ok(engine.includes("mode:'rpCycle'")&&engine.includes('Sn ↔ Sb ↔ Te'),'ciclo terminal Sn–Sb–Te está configurado');
ok(engine.includes("fuel:'H'")&&engine.includes("fuel:'p'"),'há fases com H ionizável e com prótons livres');
ok(engine.includes('ionizeRpHydrogen')&&engine.includes('H → p + e⁻'),'ionização de Hidrogênio está implementada');
ok(engine.includes('rpPhotoReturns++')&&engine.includes('photodisintegration'),'competição (γ,p) está implementada');
ok(engine.includes("rpWaitDecays>=1")&&engine.includes("rpCyclesObserved>=1"),'waiting point e ciclo exigem observação antes de concluir');
ok(engine.includes("seedCount:1,menuTag:step.to")&&engine.includes("const step=rpStep(s),cells=activeCells().slice(),used=new Set(),seedCount=1"),'cada fase rp começa com exatamente uma semente direta');
ok(engine.includes("RP_FOUNDATION_STEPS")&&engine.includes("from:'Fe',to:'Co'")&&engine.includes("from:'Co',to:'Ni'"),'rp-process reconstrói Ni a partir da semente-base de Ferro');
ok(engine.includes("const hasRpRoute=[...state.pieces.values()].some")&&engine.includes("createPiece('Fe',cell,true)"),'segurança do rp-process repõe apenas matéria-base, nunca o precursor direto');
ok(engine.includes("configureSingleObjectiveIngredients(PHASES)")&&engine.includes("p.starterGroups=[[p.seed],...Array.from({length:baseCount},()=>['Fe'])]"),'fases s/r recebem uma única semente direta e Ferro para reconstrução');
ok(engine.includes("foundation_weak_s")&&engine.includes("foundation_agb_s")&&engine.includes("foundation_r"),'processos de nêutrons possuem rotas agregadas de reconstrução a partir de Ferro');
ok(engine.includes("configureNeutronGameplay(PHASES)")&&engine.includes("neutronPattern:'")===false,'mecânicas de nêutrons são configuradas por templates globais, não duplicadas nas fases');
ok(engine.includes("source22")&&engine.includes("Ne22")&&engine.includes("²²Ne + ⁴He → ²⁵Mg + n"),'fonte ²²Ne(α,n) está implementada');
ok(engine.includes("source13")&&engine.includes("C13")&&engine.includes("¹³C + ⁴He → ¹⁶O + n"),'fonte ¹³C(α,n) está implementada');
ok(engine.includes("scheduleNeutronBeta")&&engine.includes("resolvePendingNeutronBetas")&&engine.includes("neutronBetaPending"),'espera β− usa estado nuclear pendente');
ok(engine.includes("requiresNeutronBranch")&&engine.includes("captura antes do β−")&&engine.includes("neutronBranchesObserved"),'ramificações permitem captura antes de β−');
ok(engine.includes("neutronShellExposure")&&engine.includes("CASCA ATRAVESSADA")&&engine.includes("EXPOSIÇÃO"),'cascas mágicas exigem exposição acumulada');
ok(engine.includes("neutronPulseSize")&&engine.includes("spawnNeutronBatch")&&engine.includes("pulseStrong"),'pulsos de nêutrons variam o fluxo do processo-s');
ok(engine.includes("rStorm")&&engine.includes("rWave")&&engine.includes("neutronStormsObserved"),'processo-r possui tempestades e ondas de nêutrons');
ok(engine.includes("rFreezeout")&&engine.includes("FREEZE-OUT")&&engine.includes("neutronFreezeouts"),'freeze-out do processo-r está implementado como etapa própria');
ok(engine.includes("p.neutronBetaPending&&neutronGameplay(s).pattern!=='branch'"),'núcleos aguardando β− bloqueiam recaptura fora de ramificações');
ok(engine.includes("COULOMB_BLOCK_CHANCE_BY_RING=Object.freeze({0:0,1:0,2:.5,3:.6,4:.8})"),'Barreira de Coulomb usa 0/0/50/60/80% por camada');
ok(engine.includes("if(s.id==='coulomb_intro')return ring<=2?0:1"),'tutorial mantém Barreira de Coulomb determinística: anéis 0–2 livres e 3–4 bloqueados');
ok(engine.includes("COULOMB_EXEMPT_SYMS=new Set(['H','D','T'])"),'H, Deutério e Trítio permanecem isentos da Barreira de Coulomb');
ok(engine.includes('coulombRollBlocks(blockedCell,s,blockedPiece.sym)')&&engine.includes('coulombRollBlocks(cell,s,target.sym)'),'fusão e captura de prótons usam a chance radial da Barreira de Coulomb');
ok(engine.includes("coulomb:{title:'BARREIRA DE COULOMB',text:'Aproxime os átomos do núcleo estelar para diminuir a resistência.'}"),'tooltip da Barreira de Coulomb usa sempre a mensagem didática fixa');
ok(html.includes('assets/css/ardua.css')&&html.includes('assets/js/ardua.js'),'index.html continua apontando para assets estáticos');
ok(engine.includes("['Próton','Próton','(+)']")&&engine.includes("['n','Nêutron','(n)']")&&engine.includes("['γ','Fóton gama','γ']"),'receitas mantêm nomes e símbolos em representações separadas');
ok(engine.includes("['p','Próton','(+)']")&&engine.includes("['n','Nêutron','(n)']"),'tokens nucleares p/n usam (+)/(n)');
ok(engine.includes("add(e.name.toLocaleLowerCase('pt-BR'),e.name,symbol)")&&engine.includes("(?=$|[\\\\s+→/·,)])\`,'g');"),'símbolos químicos diferenciam maiúsculas de partículas minúsculas');
ok(engine.includes("return{name:restore('name'),symbol:restore('symbol')}")&&engine.includes('function recipeSymbolLine(label)'), 'formatador gera linha nominal e linha simbólica');
ok(engine.includes('class="recipe-name-line"')&&engine.includes('class="recipe-symbol-line"'),'HUD renderiza receitas em duas linhas');
ok(engine.includes("sub:headerRecipeLine(modalPrimaryLine(s))"),'modal de abertura preserva a linha nominal compacta');
ok(engine.includes('async function relocateNewbornCoreProduct()')&&engine.includes('const center=(byRing[0]||[])[0]')&&engine.includes('const ringOne=(byRing[1]||[])'),'produto recém-formado no núcleo central é deslocado para a primeira camada');
ok(engine.includes('const relocated=await relocateNewbornCoreProduct()')&&engine.includes('protectedPieceIds:protectedIds'),'produto deslocado do núcleo fica protegido do pulso gravitacional da mesma reação');
ok(engine.includes("if(s.mode==='primordialNuclear')return{p:2,n:2,e:0}")&&engine.includes("if(s.mode==='atomicRecombination'||s.mode==='primordialMolecule')return{p:2,n:2,e:2}"),'matéria-base primordial mantém piso renovável sem repor intermediários');
ok(engine.includes('ensureBaseMatterReserve(phase())')&&engine.includes('const baseMatterChanged=ensureBaseMatterReserve(s)'),'reserva de matéria-base é reavaliada após reações e na recuperação de oportunidades');
ok(engine.includes("const molecularFuel=s.id==='first_atomic_bonds'?{p:9,e:9,n:6}:{p:6,e:6,n:2}"),'fase molecular posterior preserva nêutrons suficientes para reconstruir a cadeia primordial');
ok(engine.includes("pairCount<=3?2:pairCount<=9?3:pairCount<=18?4:5")&&engine.includes("pairCount<=3?2:pairCount<=9?4:pairCount<=18?5:6"),'formação estelar limita grupos simultâneos conforme a escala da estrela');
ok(engine.includes("const cap=spec.pairCount<=3?38:spec.pairCount<=9?36:spec.pairCount<=18?32:30")&&engine.includes("fit=starSize()*.72/(2*spec.radius+3)"),'átomos da formação usam escala visual menor e adaptativa');
ok(engine.includes('function stellarFormationSoftSeparate(f,dt)')&&engine.includes(")*.62"),'grupos independentes recebem separação suave sem colisão rígida');
ok(engine.includes('function stellarFormationEntryPoint(f)')&&engine.includes('spawnRadius=center+stellarFormationAtomSize(f.spec)*1.35'),'novas duplas entram pela borda externa do campo');
ok(engine.includes('function stellarFormationScheduleSupply(f,delay=620)')&&engine.includes("stellarFormationSpawnPair(f,{incoming:true})"),'novas duplas chegam gradualmente após liberar espaço');
ok(engine.includes('for(let i=0;i<spec.initialGroups;i++)stellarFormationSpawnPair(f,{incoming:false})'),'formação não cria toda a matéria de uma vez');
ok(formationCss.includes('.formation-atom::before')&&formationCss.includes('inset:-7px'),'átomos menores preservam uma área clicável confortável');
ok(formationCss.includes('.formation-atom.formation-incoming')&&formationCss.includes('.formation-g-field.formation-incoming'),'matéria em entrada possui estado visual próprio');
ok(engine.includes('function primordialParticleDropTarget(p)')&&engine.includes('executePrimordialParticleDrop(p,target)'),'partículas primordiais podem reagir ao serem soltas sobre parceiro compatível');
ok(engine.includes("startX:pt.x,startY:pt.y")&&engine.includes("Math.hypot(pt.x-d.startX,pt.y-d.startY)>=7"),'partículas primordiais ativam arraste imediatamente após movimento intencional');
ok(engine.includes("target.mode==='bindElectron'")&&engine.includes("target.mode==='recombineH'"),'drag primordial cobre recombinação H e captura eletrônica em íons');
ok(engine.includes('function primordialFreeDragTarget(d)')&&engine.includes("target.mode==='heh'")&&engine.includes("target.mode==='h+heh'"),'núcleos, átomos e moléculas primordiais possuem drag reativo próprio');
ok(engine.includes("Math.hypot(pt.x-d.startX,pt.y-d.startY)<7"),'arraste primordial preserva clique com limiar de movimento');
ok(engine.includes('function stellarFormationGroupDraggable(g){return !!g&&!g.incoming&&g.members.length<=12}'),'aglomerados estelares acima de 12 H ficam ancorados');
ok(engine.includes('function stellarFormationDragTarget(f,g)')&&engine.includes('finishStellarFormationDrag(atomId,ev,cancel=false)'),'formação gravitacional une grupos compatíveis por drag e soltura');
ok(engine.includes("if(a.id===dragged||b.id===dragged)continue"),'separação suave não disputa controle com o grupo arrastado');
ok(formationCss.includes('touch-action:none')&&formationCss.includes('.formation-g-field.drag-target')&&formationCss.includes('.formation-atom.dragging'),'drag gravitacional tem gesto móvel e feedback visual próprios');
ok(fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8').includes('.atom.drop-target')&&fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8').includes('.atom.primordial-dragging'),'drag primordial destaca alvo e suspende a flutuação visual durante o gesto');
ok(engine.includes('function stellarBoardDragTarget(d,x=d?.logicalX??d?.x,y=d?.logicalY??d?.y)')&&engine.includes("target?.type==='move'")&&engine.includes('moveSelectedAtom(target.cell)'),'tabuleiro estelar usa drag para movimento real em célula vizinha');
ok(engine.includes('function stellarBoardAdjacentFusionTarget(source,target,s=phase())')&&engine.includes("target?.type==='fusion'")&&engine.includes('setTimeout(()=>fuse(recipe),95)'),'tabuleiro estelar usa drag para fusão adjacente sem criar rota paralela');
ok(engine.includes('function stellarBoardAdjacentSwapTarget(source,target,s=phase())')&&engine.includes("target?.type==='swap'")&&engine.includes('swapBoardPieces(d.sourceCell,target.cell)'),'tabuleiro estelar troca núcleos vizinhos comuns por drag');
ok(engine.includes('async function swapBoardPieces(sourceCell,targetCell)')&&engine.includes('protectedPieceIds:[sourceId,targetId]'),'swap estelar custa uma rodada e protege os dois núcleos do pulso gravitacional imediato');
ok(engine.includes('stellarBoardAdjacentReactionCandidate(source,target,s=phase())')&&engine.includes('possibleRecipes([source.sym,target.sym]).length>0'),'swap preserva prioridade de reação e de prefixos de receitas cumulativas');
ok(engine.includes("if(!(neigh[source.cell]||[]).includes(target.cell))return null"),'drag de fusão estelar exige reagentes adjacentes e não teletransporta matéria');
ok(engine.includes("Math.hypot(pt.x-d.startX,pt.y-d.startY)<7"),'drag do tabuleiro preserva toque curto com limiar de movimento');
ok(engine.includes("el.dataset.cell=p.cell===null||p.cell===undefined?'':String(p.cell)"),'átomos do tabuleiro expõem a célula atual para interação e testes');
ok(fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8').includes('.atom.stellar-board-dragging')&&fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8').includes('.cell.stellar-drag-hover')&&fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8').includes('.atom.stellar-board-swap-target'),'tabuleiro estelar mostra origem arrastada, movimento e alvo neutro de troca');

ok(engine.includes('const RewardDirector=Object.freeze')&&engine.includes('const DiscoverySystem=Object.freeze')&&engine.includes('const AdaptiveAudio=Object.freeze'),'diretor de recompensas, descobertas e áudio adaptativo são globais');
ok(engine.includes("state.rewardDiscoveries")&&engine.includes("rewardAchievements")&&engine.includes("signatureSeen"),'Atlas e marcos audiovisuais persistem no save');
ok(engine.includes("state.chainCalloutTimer=setTimeout")&&engine.includes("},1850)"),'texto de cascata permanece legível por aproximadamente 1,85 s após a última atualização');
ok(engine.includes("CHAIN_AUTO_FLOW_FACTORS=Object.freeze([.25,.10,0])")&&engine.includes('CHAIN_MAX_PROGRESS_BONUS=.10'),'cascatas preservam crédito decrescente e teto de 10% do flowTarget');
ok(engine.includes('CHAIN_OBJECTIVE_PROGRESS_FLOOR=.75'),'objetivo científico preserva piso de 75% sem encerrar a fase sozinho');
ok(engine.includes("preparedContinuationForFusion")&&engine.includes("phenomenon:plannedChain"),'cadeias previamente posicionadas podem ser reconhecidas como rede preparada');
ok(engine.includes("playScientificSignature('supernova')")&&engine.includes("playScientificSignature('neutronStar')")&&engine.includes("playScientificSignature('blackHole')"),'Supernova, Estrela de Nêutrons e Buraco Negro possuem momentos de assinatura');
ok(engine.includes("C:'carbon'")&&engine.includes("Fe:'iron'")&&engine.includes("Au:'gold'")&&engine.includes("U:'uranium'"),'Carbono, Ferro, Ouro e Urânio possuem assinaturas científicas');
ok(engine.includes("setTimeout(()=>{if(phase()===s&&state.readyToAdvance)$('phaseEndBtn').classList.add('show')},720)"),'avanço da fase espera o beat audiovisual de conclusão');
ok(html.includes('id="discoveryAtlas"')&&html.includes('Atlas de descobertas'),'menu contém Atlas de descobertas persistente');
const css=fs.readFileSync(path.join(root,'assets/css/ardua.css'),'utf8');
ok(css.includes('.chain-callout')&&css.includes('.reward-progress-aura')&&css.includes('.reward-spark'),'hierarquia visual inclui callout, aura persistente e partículas contidas');
ok(css.includes('@media(prefers-reduced-motion:reduce)'),'efeitos respeitam preferência de redução de movimento');
ok(engine.includes('function objectiveProgress(s=phase())')&&engine.includes('const done=objectiveSatisfied(s);if(done)return 1'),'barra possui progresso científico próprio e só libera 100% com objetivo satisfeito');
ok(engine.includes('const objective=objectiveProgress(s)')&&engine.includes('return Math.min(objective,flow)*100'),'PROGRESSO usa o menor avanço entre objetivo científico e flow');
ok(engine.includes("state.readyToAdvance?100:Math.min(99,Math.floor(p))"),'texto da barra não arredonda uma fase incompleta para 100%');
ok(engine.includes("fragilePhase.uniqueMatterObjective=true")&&engine.includes('objectiveLineages:new Set()'),'fase de Be-8 usa objetivo por linhagem de matéria');
ok(engine.includes('function mergeMatterLineages')&&engine.includes('function creditObjectiveLineage'),'proveniência de matéria é herdável e creditada por linhagem');
ok(engine.includes("createPiece('He',origin,false,{lineage})")&&engine.includes("createPiece('He',secondCell,false,{lineage})"),'decaimento de Be-8 devolve Hélios com a mesma proveniência');
ok(engine.includes("teachProductOnce('recycledMatter',t.x,t.y)")&&engine.includes('MATÉRIA RECICLADA · sem novo crédito'),'reciclagem repetida permanece válida mas não farma o objetivo');
ok(engine.includes('CHAIN_LESSON_BY_KIND')&&engine.includes('await teachChainEffectOnce(kind,product.x,product.y)'),'primeira cascata pausa para explicação antes da continuação automática');
ok(engine.includes("await teachProductOnce('neutronSource',at.x,at.y)")&&engine.includes("await teachProductOnce('freezeout',p.x,p.y)")&&engine.includes("await teachProductOnce('branching',p.x,p.y)"),'fontes, freeze-out e ramificações recebem tooltip antes do efeito');
ok(engine.includes("if(viable&&!photoReturn&&route.rp&&route.pattern==='waiting')await teachProductOnce('waitingPoint',target.x,target.y)"),'waiting point é explicado antes da animação de captura');
ok(engine.includes('const ObjectiveReactionMotif=Object.freeze')&&engine.includes("if(s.mode!=='fusion')return[]"),'Reaction Motif é um sistema global mas só escolhe receitas-alvo de fusão manual');
ok(engine.includes('r?.out===s.new')||engine.includes('r.out===s.new'),'receita-alvo do motif precisa produzir o objetivo científico da fase');
ok(engine.includes('state.chainAutoContext')&&engine.includes('objectiveMotifReactionEligible'),'cascatas automáticas não recebem a cerimônia completa do objetivo');
ok(engine.includes('objectiveMotifArmFirst(p)')&&engine.includes('objectiveMotifArmSecond(ex,[...state.selected])'),'primeiro e segundo reagentes da receita-alvo disparam notas próprias');
ok(engine.includes('objectiveMotifPlayNote(r,2)')&&engine.includes('objectiveMotifChord(ctx.r'),'alinhamento toca a terceira nota e o produto resolve com o acorde das três notas');
ok(engine.includes('objectiveMotifSelectionReady(r,cells)')&&engine.includes('objectiveLineageIsFresh'),'motif exige seleção manual pronta e respeita a proveniência anti-reciclagem');
ok(engine.includes('objectiveMotifBarrierBlocked(blockedPiece,r)'),'Barreira de Coulomb interrompe a resolução musical e rearma a tentativa');
ok(engine.includes('await objectiveMotifPrepare')&&engine.includes('await objectiveMotifConverge')&&engine.includes('await objectiveMotifReveal'),'reação-objetivo possui timeline visual preparar → convergir → revelar');
ok(css.includes('/* Objective Reaction Motif */')&&css.includes('.objective-motif-nucleus.result.visible'),'CSS contém a cerimônia visual central da reação-objetivo');
ok(engine.includes('window.AudioContext||window.webkitAudioContext')&&engine.includes("ctx.state==='suspended'")&&engine.includes('ctx.resume()'),'áudio do Reaction Motif desbloqueia e retoma Web Audio de forma compatível');
ok(engine.includes("stage.className='objective-motif-stage';dom.star.appendChild(stage)"),'palco do Reaction Motif fica acima das camadas de partículas');
ok(css.includes('.star-board.objective-motif-active .primordial-layer')&&css.includes('.star-board.objective-motif-active .neutrons')&&css.includes('.star-board.objective-motif-active .cosmic-rays'),'prótons, nêutrons e partículas flutuantes perdem contraste durante a cerimônia');
ok(css.includes('.objective-motif-stage{position:absolute;inset:0;z-index:120'),'Reaction Motif usa camada visual superior dedicada');
ok(engine.includes("d=index===2?.28:.24")&&engine.includes("g=index===2?.086:.074")&&engine.includes("tone(f*2,d*.82,'sine',g*.30)"),'notas de seleção e alinhamento do Reaction Motif têm presença reforçada e harmônico audível');
ok(engine.includes("tone(f,.52,'triangle',.040)")&&engine.includes("tone(f*2,.42,'sine',.014)"),'acorde final do Reaction Motif possui corpo e reforço harmônico próprios');
ok(engine.includes("renderPieces();const motifGridProduct=dom.pieces.querySelector")&&engine.includes("motifGridProduct.classList.add('motif-grid-product')"),'produto real da grade é renderizado sob a cerimônia antes do handoff');
ok(engine.includes("grid.classList.remove('motif-grid-product')")&&engine.includes("grid.classList.add('motif-grid-ready')"),'fim da cerimônia revela o produto já existente na grade sem segunda transformação');
ok(css.includes('/* Objective Motif grid handoff */')&&css.includes('.atom.motif-grid-product')&&css.includes('.atom.motif-grid-ready'),'CSS contém handoff instantâneo entre produto central e produto da grade');
ok(engine.includes('const ObjectiveInteractionMotif=Object.freeze')&&engine.includes('objectiveInteractionImpact'),'Objective Interaction Motif generaliza a cerimônia para interações manuais');
ok(engine.includes('reactPrimordialParticlePair')&&engine.includes('primordial:${s.id}:${r.out}')&&engine.includes('reactPrimordialMixed'),'Universo primordial usa a cerimônia nas receitas que avançam o objetivo');
ok(engine.includes('atomic:${s.id}:H')&&engine.includes("'e⁻','CAPTURA'"),'Era atômica usa a cerimônia em recombinação e captura eletrônica');
ok(engine.includes('atlas:${sp.id}')&&engine.includes('atlas-inaccessible:${sp.id}')&&engine.includes("'×','SEM FUSÃO'"),'Atlas de fusões usa motivo em produtos e observações sem fusão');
ok(engine.includes('neutron-source:${s.id}:${g.source}')&&engine.includes('objectiveInteractionNeutronToken(n)'),'processo-s usa a cerimônia na fonte e nas capturas de nêutrons');
ok(engine.includes("'n','EXPOSIÇÃO'")&&engine.includes("'n','CAPTURA'"),'capturas de nêutrons e exposição de casca usam feedback audiovisual');
ok(engine.includes("'p','CAPTURA'")&&engine.includes('proton-fusion:${phase().id}:${r.out}'),'prótons livres usam a cerimônia em captura e fusão assistida');
ok(engine.includes('objectiveInteractionCosmicToken(ray,s)')&&engine.includes('energetic:${s.id}:${source}:${resultSym}'),'raios cósmicos, neutrinos e fótons gama usam a mesma cerimônia');
ok(css.includes('/* Objective Interaction Motif extensions */')&&css.includes('.objective-motif-token.particle')&&css.includes('.objective-motif-active .motif-source'),'CSS inclui partículas ampliadas e perda de contraste das fontes originais');

ok(engine.includes("proton:{title:'PRÓTON LIBERADO',text:'Algumas transformações devolvem prótons que podem participar de novas reações.'}"),'tooltip de próton usa o texto simplificado');
ok(engine.includes("gamma:{title:'FÓTON GAMA (γ)',text:'Raios gama são fótons emitidos por núcleos quando excesso de energia é liberado.'}"),'tooltip de raio gama usa o texto revisado');
ok(engine.includes("kind==='p'?'+'"),'próton aparece como + no Objective Interaction Motif');
ok(engine.includes('function playBigBangOverture()')&&engine.includes('phrase(170,110)')&&engine.includes('playBigBangOverture();vibrate'),'Big Bang possui abertura musical em frases e acorde de resolução');
ok(engine.includes('function rewardDirectorNeedsContinue')&&engine.includes("'OBJETIVO CIENTÍFICO','MARCO','ATLAS ATUALIZADO'"),'notificações científicas exigem confirmação explícita');
ok(engine.includes("$('ambientContinueBtn').addEventListener('click',rewardDirectorDismiss)")&&html.includes('id="ambientContinueBtn"'),'banner persistente possui botão CONTINUAR funcional');
ok(css.includes('.ambient-banner.awaiting-continue')&&css.includes('.ambient-continue[hidden]'),'CSS permite interação somente quando a notificação aguarda confirmação');
ok(engine.includes('A colisão entre ${a} e ${b} pode seguir mais de um caminho e produzir diferentes elementos.'),'tooltip de canais concorrentes foi simplificado');
console.log('\nValidação estática do Ardua concluída.');
