from pathlib import Path
p=Path('scripts/apply-movement-chain-particles.py')
s=p.read_text(encoding='utf-8')
s=s.replace('prog="  if(s.mode===\'opening\')return 0;"','prog="if(s.mode===\'opening\')return 0;"')
s=s.replace('prog+"\\n  if(s.mode===\'movementTutorial\')return 0;"','prog+"\\n if(s.mode===\'movementTutorial\')return 0;"')
s=s.replace('primary="function modalPrimaryLine(s=phase()){\\n  if(s.mode===\'stellarFormation\')return \'Atraia moleculas com a gravidade\';"','primary="function modalPrimaryLine(s=phase()){\\n if(s.mode===\'stellarFormation\')return \'Atraia moleculas com a gravidade\';"')
s=s.replace('primary2="function modalPrimaryLine(s=phase()){\\n  if(s.mode===\'movementTutorial\')return \'Leve o Hélio até o núcleo estelar.\';\\n  if(s.mode===\'stellarFormation\')return \'Atraia moleculas com a gravidade\';"','primary2="function modalPrimaryLine(s=phase()){\\n if(s.mode===\'movementTutorial\')return \'Leve o Hélio até o núcleo estelar.\';\\n if(s.mode===\'stellarFormation\')return \'Atraia moleculas com a gravidade\';"')
s=s.replace('secondary="function modalSecondaryLine(s=phase()){\\n  if(s.mode===\'stellarFormation\')return \'\';"','secondary="function modalSecondaryLine(s=phase()){\\n if(s.mode===\'stellarFormation\')return \'\';"')
s=s.replace('secondary2="function modalSecondaryLine(s=phase()){\\n  if(s.mode===\'movementTutorial\')return \'Selecione o Hélio e escolha uma célula vazia vizinha até chegar ao centro.\';\\n  if(s.mode===\'stellarFormation\')return \'\';"','secondary2="function modalSecondaryLine(s=phase()){\\n if(s.mode===\'movementTutorial\')return \'Selecione o Hélio e escolha uma célula vazia vizinha até chegar ao centro.\';\\n if(s.mode===\'stellarFormation\')return \'\';"')
p.write_text(s,encoding='utf-8')
print('movement migration anchors hardened')
